name: Run Unit Tests and Dockerfile
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
      - uses: actions/checkout@v3
      - name: List contents of directory
        run: ls -al
      - name: Run Unit Tests
        run: python3 -m unittest test_functions.py
      - name: Build Docker Container
        run: docker build -t test-container:1.0
      - name: Run Docker Container
        run: docker run test-container:1.0


