name: Unit Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      name: Set up Python 3.10 and Run Tests
      uses: actions/setup-python@v4
        with:
          python-version: 3.10
      uses: actions/checkout@v3
      run: ls -al
      run: python3 test_functions.py

